[package]
name = "ipfs-manager"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
parking_lot = { workspace = true }
log = "0.4.17"
tempfile = "3.2.0"
regex = "1.5"

[build-dependencies]
fs_extra = "1.2.0"